/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#00515d",
        "on-background": "#e5e1e4",
        "secondary-container": "#00cbe6",
        "on-primary-fixed": "#23005c",
        "on-primary-container": "#340080",
        "inverse-on-surface": "#313032",
        "secondary": "#5de6ff",
        "surface-container-highest": "#353437",
        "on-primary": "#3c0091",
        "on-error": "#690005",
        "on-secondary-fixed": "#001f25",
        "on-tertiary-fixed": "#3d0026",
        "primary-fixed-dim": "#d0bcff",
        "error-container": "#93000a",
        "surface-tint": "#d0bcff",
        "secondary-fixed-dim": "#2fd9f4",
        "surface-dim": "#131315",
        "surface-container-high": "#2a2a2c",
        "primary-container": "#a078ff",
        "on-tertiary-fixed-variant": "#85145a",
        "surface-container": "#201f22",
        "inverse-primary": "#6d3bd7",
        "background": "#131315",
        "surface-bright": "#39393b",
        "on-surface-variant": "#cbc3d7",
        "tertiary-container": "#e364a7",
        "on-tertiary-container": "#560038",
        "on-surface": "#e5e1e4",
        "tertiary-fixed": "#ffd8e7",
        "on-tertiary": "#620040",
        "surface-container-low": "#1c1b1d",
        "tertiary-fixed-dim": "#ffafd3",
        "surface": "#131315",
        "surface-container-lowest": "#0e0e10",
        "secondary-fixed": "#a2eeff",
        "outline-variant": "#494454",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#5516be",
        "primary-fixed": "#e9ddff",
        "on-secondary": "#00363e",
        "inverse-surface": "#e5e1e4",
        "error": "#ffb4ab",
        "surface-variant": "#353437",
        "primary": "#d0bcff",
        "on-secondary-fixed-variant": "#004e5a",
        "outline": "#958ea0",
        "tertiary": "#ffafd3"
      },
      "spacing": {
        "sm": "12px",
        "gutter": "24px",
        "lg": "40px",
        "xs": "4px",
        "base": "8px",
        "xl": "64px",
        "margin": "32px",
        "md": "24px"
      },
    },
  },
  plugins: [],
}
